### ISSUE TITLE
CLI: Boards of height >= 10 and/or width >= 10 display alignment issues

### ISSUE THREAD

**Issue by Coteh** [Coteh/MinesweeperClone#1]
Since the cli board drawing only takes into account single digits, any dimension number with more than one digit will result in shifted rows/columns.

![image](https://cloud.githubusercontent.com/assets/3276350/11726574/3aa30314-9f4d-11e5-9cc2-2fc2476edb8f.png)

To fix:
- Add additional spaces (or zeros) to each row indicator number that has less digits than the highest amount of digits for a row number
- For columns, add additional spaces (or zeros) to each column indicator number that has less digits than the highest amount of digits for a column number

**Comment by jakedeichert** [comment]
AKA "string padding"

**Comment by Coteh** [comment]
Thanks Jake! (Y)
